import { salas } from "@/data/salas";

export const users = [
    {
        id: 1,
        nome: 'NeymarJr',
        pfp: 'https://static.wikia.nocookie.net/famosos/images/d/d6/Neymar_-_Official_Portrait_FWC26_cropped.png/revision/latest?cb=20260614023953&path-prefix=pt-br',
        banner: 'https://i.superesportes.com.br/Mma7tYFtvyrY4-HEGSiI4Q2-Zgk=/650x0/smart/imgsapp.mg.superesportes.com.br/app/noticia_126420360808/2022/11/22/3980504/neymar_1_87520.jpg',
        desc: 'menino ney.',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 67,
        seguindo: 69
    },
    {
        id: 2,
        nome: 'Krasue',
        pfp: 'https://m.media-amazon.com/images/I/71Rblev0nXL.png',
        banner: 'https://deadbydaylight.com/static/a197e7b8b44bfbe199546300338aeffb/691d2/MAPLE_Keyart_Resizes_WEBSITE_Keyart_1920x1080_V3_b1b5d017c9.png',
        desc: 'uma mulher com hábitos noturnos exóticos',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 1,
        seguindo: 0
    },
    {
        id: 3,
        nome: 'fbigatito',
        pfp: 'https://chemitec.com.br/wp-content/uploads/2025/04/como-cuidar-de-gatos-filhotes.jpg',
        banner: 'https://t4.ftcdn.net/jpg/05/40/20/91/360_F_540209110_YNGwMb4Q7zdqsYPmoP7gMnXtrXjKcIrS.jpg',
        desc: 'apenas um gato normal.',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 19,
        seguindo: 10
    },
    {
        id: 4,
        nome: 'Lara Croft',
        pfp: 'https://www.tombraider.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2Fx77ixfmkpoiv%2F5p9aOWyaNeQHlZHCCKgYQE%2F8f3782a868382c9639f3d7723a5ee71d%2FTomb-Raider-2-Box-Art-1x1-min.png&w=3840&q=75',
        banner: 'https://p2.trrsf.com/image/fget/cf/1200/900/middle/images.terra.com/2022/05/20/lara-croft-1h7gdz69qqn90.jpg',
        desc: 'Arqueóloga formada!',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 107,
        seguindo: 2
    },
    {
        id: 5,
        nome: 'Amanda Young',
        pfp: 'https://64.media.tumblr.com/c80596d4aa5bb25c36e3f40ab9c81da7/37c4bce1688e138d-b9/s1280x1920/c2aeb3dbdf290f584ef380b5822816106d68cf56.jpg',
        banner: 'https://i0.wp.com/miniporco.com.br/wp-content/uploads/2026/01/unnamed-2-2.jpg?w=640&ssl=1',
        desc: 'Bióloga formada! e gosto de porcos',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 4,
        seguindo: 12
    },
    {
        id: 6,
        nome: 'Bay-harbor Butcher',
        pfp: 'https://m.media-amazon.com/images/M/MV5BOTZhNTdlOTMtZGU4YS00NTIxLTk1MzMtYjk5OWQyYzMxOGFjXkEyXkFqcGc@._V1_QL75_UY281_CR131,0,190,281_.jpg',
        banner: 'https://cinebuzz.com.br/wp-content/uploads/2025/07/dexter-ressurreicao-traz-dexter-morgan-de-volta-a-vida-e-surpreende-fas.jpg',
        desc: 'não sou o dexter',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 93,
        seguindo: 114
    },
    {
        id: 7,
        nome: 'Surprise mf',
        pfp: 'https://i.pinimg.com/736x/ea/e7/b0/eae7b0dd163140feadfd37930f6e9b79.jpg',
        banner: 'https://static0.srcdn.com/wordpress/wp-content/uploads/2022/01/james-doakes-dexter-new-blood-finale-montage.jpg?q=49&fit=contain&w=750&h=422&dpr=2',
        desc: 'eu sei que tem algo de errado com o dexter',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 115,
        seguindo: 1
    },
    {
        id: 8,
        nome: 'Mãe do barry',
        pfp: 'https://static.wikia.nocookie.net/anicrossbr/images/c/c9/YF22Ekg.jpg/revision/latest?cb=20160514223246&path-prefix=pt-br',
        banner: 'https://ovicio.com.br/wp-content/uploads/2023/05/20230525-c3hnptingdlomybbwiuqrp-730x365.jpg',
        desc: 'era eu barry',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 28,
        seguindo: 66
    },
    {
        id: 9,
        nome: 'Mãe do barry',
        pfp: 'https://static.wikia.nocookie.net/arrow/images/f/f8/For%C3%A7a_Nora_Allen.png/revision/latest?cb=20240316054058&path-prefix=pt-br',
        banner: 'https://i.pinimg.com/736x/c5/e4/0e/c5e40e88dc3584399305ebeb83a3f5c6.jpg',
        desc: 'mãe do barry allen da serie do flash',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 32,
        seguindo: 1090
    },
    {
        id: 10,
        nome: 'sackboy',
        pfp: 'https://i.pinimg.com/736x/db/44/45/db4445533f830b92cf6f40c0296c79f1.jpg',
        banner: 'https://i.pinimg.com/736x/24/1a/ea/241aeadd7c5900aac8c740010c8a1c9b.jpg',
        desc: 'pqp denovo nao',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 67,
        seguindo: 67
    },
    {
        id: 11,
        nome: 'o inimigo',
        pfp: 'https://content.imageresizer.com/images/memes/Buddy-satan-meme-5.jpg',
        banner: 'https://aventurasnahistoria.com.br/wp-content/uploads/demoniocapafilme2.jpg',
        desc: 'fale palavrão minha criança',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 666,
        seguindo: 666
    },
    {
        id: 12,
        nome: 'frisk1',
        pfp: 'https://i.pinimg.com/736x/ce/40/ac/ce40ac6e9f33b5af97d9c26b78cf3779.jpg',
        banner: 'https://image.api.playstation.com/vulcan/ap/rnd/202508/1316/e99168bdab3ac4f8804b8a92032c2e95e5187d0b0d92fff6.jpg?w=1920&thumb=false',
        desc: 'odeio self-insert',
        mostrarSala: 'sim',
        sala1: '22info22',
        sala2: 'Five Nights At Freddy',
        sala3: null,
        seguidores: 76,
        seguindo: 490
    },
    {
        id: 13,
        nome: 'homotron3000',
        pfp: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZ96tZagiInGJY7vKHkbvao_Q7OIQ4Q8Fq9ZHqo35pC6-dJX3bCpnPc4I&s=10',
        banner: 'https://cdn.kobo.com/book-images/e0a84b50-7fa0-49dd-a0ad-2e94d2b8904f/353/569/90/False/lgbt-1.jpg',
        desc: 'bip bip conectando aos servidores da argelia',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 109,
        seguindo: 230
    },
    {
        id: 14,
        nome: 'Gabriel',
        pfp: 'https://media.istockphoto.com/id/614333298/pt/foto/funny-nerd-or-geek-have-an-idea.jpg?s=612x612&w=0&k=20&c=8vcAO_oYkfPT7ZxsjnFWsAuecaFZ_3c8VvoMSTj7fvQ=',
        banner: 'https://pt.quizur.com/_image?href=https://static.quizur.com/i/b/5a8c20a9600d97.302390645a8c20a942ffb6.76737408.jpg&w=1200&h=900&f=webp',
        desc: 'vocês preferem sorvete de morango ou de bosta',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 314,
        seguindo: 932
    },
    {
        id: 15,
        nome: 'Edwin',
        pfp: 'https://media.forgecdn.net/attachments/description/1366638/description_38d6f30d-f853-469f-89c9-591cf6d00a5d.jpg',
        banner: 'https://i.pinimg.com/736x/f5/50/34/f5503432e88456b6f143040aa7c5196e.jpg',
        desc: 'eu não quero bosta',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 59,
        seguindo: 87
    },
    {
        id: 16,
        nome: 'kaori',
        pfp: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5cgtM6CQjM7x5pfPruPWMT5xhX7J-f_dkVeEtQ75_JVnrwFT64DXn0As&s=10',
        banner: 'https://miro.medium.com/v2/0*AODaFOtQp_4WvKct.jpg',
        desc: 'luto Kaori, 14 anos. Primária Arima',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 149,
        seguindo: 1
    },
    {
        id: 17,
        nome: 'Wilhelm',
        pfp: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeBzYJ6K8YtGWT8Ey9wrqsibvpUz4aL9LlZdLnHfbNiQ&s=10',
        banner: 'https://kdfrases.com/frases-imagens/frase-nada-e-real-a-nao-ser-o-sonho-e-o-amor-anne-noailles-151740.jpg',
        desc: 'Ninguém é real',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 1244543,
        seguindo: 1
    },
    {
        id: 18,
        nome: 'Samusaax',
        pfp: 'https://static.wikia.nocookie.net/alpheapedia/images/a/a7/Lugia.png/revision/latest?cb=20210924013042',
        banner: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi9JeDlElPXQatu_198B-BSJeZxZwOKeGqAWcx4f-tIb7ogf1wZIzBJAY&s=10',
        desc: 'deus pokemon da agua',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 1,
        seguindo: 1
    },
    {
        id: 19,
        nome: 'PedroLooser',
        pfp: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ17Ejm1h6nEeS2YvXrGV_rmdFV9ulvj5LM-wbeDtmQSC8mSwEdj5OQTN4&s=10',
        banner: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdZMDaUdzTgLmr5QAeTsL4Wx14yxtjdm-fYRWcNfEpU3JKEbUfiWFu0ePu&s=10',
        desc: 'O cara do ciência todo dia',
        mostrarSala: 'sim',
        sala1: 'Ciência todo dia',
        sala2: null,
        sala3: null,
        seguidores: 0,
        seguindo: 10000
    },
    {
        id: 20,
        nome: 'Rochelixx',
        pfp: 'https://www.estrelando.com.br/uploads/2016/06/27/2-1467035574.jpg',
        banner: 'https://rollingstone.com.br/wp-content/uploads/rochelle_todo_mundo_odeia_o_chris_melhores_frases.jpg',
        desc: '1 mol de motivos para sorrir',
        mostrarSala: 'nao',
        sala1: 'Química do mal',
        sala2: null,
        sala3: null,
        seguidores: 603,
        seguindo: 99
    },
    {
        id: 21,
        nome: 'erererer',
        pfp: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTu352-ezoYGcUgARDWszoZ5G59i-WUgxwmyLuM-c27g&s',
        banner: 'https://i.ytimg.com/vi/68Ee-ls_j_0/sddefault.jpg',
        desc: 'ererererererererererer',
        mostrarSala: 'nao',
        sala1: 'Matematica',
        sala2: null,
        sala3: null,
        seguidores: 12,
        seguindo: 301
    },
    {
        id: 22,
        nome: 'usuariobobby',
        pfp: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTglFqMpY3fXwCqWvnBYGUA7LSaWfsctiPFr_VdKvmlAA&s=10',
        banner: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlHPw6CKwSGwFKXj6u4YDzwLv3odzAkX1lrsUmYhho4w&s=10',
        desc: 'meu nome é bobby',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 1945,
        seguindo: 1981
    },
    {
        id: 23,
        nome: 'coffbarneynotkillanyone',
        pfp: 'https://static.wikia.nocookie.net/animal-hospital/images/b/b8/Barney_Closeup.png/revision/latest/smart/width/250/height/250?cb=20260627123129',
        banner: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdKjfjHtgIMHo1uwL-A8_2xxUixtJXHyGrDNEjShC-OQ&s=10',
        desc: 'quero café',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 800,
        seguindo: 979
    },
    {
        id: 24,
        nome: 'sontoffolizorrone',
        pfp: 'https://vignette.wikia.nocookie.net/stranger-things/images/c/ca/Murray.jpg/revision/latest?cb=20180213110352&path-prefix=de',
        banner: 'https://i.pinimg.com/736x/4b/88/a3/4b88a371dc9130eda57ed510e3531632.jpg',
        desc: 'Assistam The Last of Us, a série',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 32,
        seguindo: 5
    },
    {
        id: 25,
        nome: 'stvgran',
        pfp: 'https://i.pinimg.com/736x/56/64/ab/5664abf13aa8167f6c910a4d259888df.jpg',
        banner: 'https://static.significados.com.br/foto/piramide-egito-antigo-significados.jpg?width=768',
        desc: 'Pode me chamar sempre que quiser, menos a noite.',
        mostrarSala: 'sim',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 2,
        seguindo: 2
    },
    {
        id: 26,
        nome: 'mrcspec',
        pfp: 'https://i.pinimg.com/736x/fe/f5/3d/fef53dbeda9099f18406fdf12f4c22b3.jpg',
        banner: 'https://static.significados.com.br/foto/piramide-egito-antigo-significados.jpg?width=768',
        desc: 'Me chame sempre que quiser, menos de dia.',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 2,
        seguindo: 2
    },
    {
        id: 27,
        nome: 'jhnlocke',
        pfp: 'https://www.cheatsheet.com/wp-content/uploads/2022/05/moon-knight-jake-lockley.jpg',
        banner: 'https://static.significados.com.br/foto/piramide-egito-antigo-significados.jpg?width=768',
        desc: 'Não me chame.',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 2,
        seguindo: 2
    },
    {
        id: 28,
        nome: 'hvm',
        pfp: 'https://i.pinimg.com/736x/27/13/22/271322c8cb72615663562377abed3767.jpg',
        banner: 'https://static0.colliderimages.com/wordpress/wp-content/uploads/2023/02/harry-potter-severus-snape-tim-roth.jpg?q=50&fit=crop&w=1232&h=693&dpr=1.5',
        desc: 'Pare de me stalkear no Kuaa Harry Potah!',
        mostrarSala: 'nao',
        sala1: null,
        sala2: null,
        sala3: null,
        seguidores: 69,
        seguindo: 9
        
    },

    
];
